"""commit

Revision ID: 048a5c41456f
Revises: 948da082c6f9
Create Date: 2024-07-19 22:37:51.224608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "048a5c41456f"
down_revision: Union[str, None] = "948da082c6f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(
        "ix_cls.__name__.lower()s_email", table_name="cls.__name__.lower()s"
    )
    op.drop_table("cls.__name__.lower()s")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cls.__name__.lower()s",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=320), nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("is_superuser", sa.BOOLEAN(), nullable=False),
        sa.Column("is_verified", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cls.__name__.lower()s_email",
        "cls.__name__.lower()s",
        ["email"],
        unique=1,
    )
    op.drop_table("users")
    # ### end Alembic commands ###
