"""Create add table

Revision ID: 948da082c6f9
Revises: 20f0df954a9c
Create Date: 2024-07-19 22:28:56.234677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "948da082c6f9"
down_revision: Union[str, None] = "20f0df954a9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cls.__name__.lower()s",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cls.__name__.lower()s_email"),
        "cls.__name__.lower()s",
        ["email"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cls.__name__.lower()s_email"),
        table_name="cls.__name__.lower()s",
    )
    op.drop_table("cls.__name__.lower()s")
    # ### end Alembic commands ###
