"""Create add 3

Revision ID: d6e4ec8c27cf
Revises: fb27a0b2dae4
Create Date: 2024-07-19 22:01:57.214731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6e4ec8c27cf"
down_revision: Union[str, None] = "fb27a0b2dae4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "count")
    # ### end Alembic commands ###
