"""add cat_id table product

Revision ID: 11410f62ca5f
Revises: c86c76ab563b
Create Date: 2024-08-12 00:32:59.256524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11410f62ca5f"
down_revision: Union[str, None] = "c86c76ab563b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "name")
    # ### end Alembic commands ###
