"""add cat_id table product

Revision ID: f205d0e53c85
Revises: 92795f17c2a3
Create Date: 2024-08-13 10:56:24.163892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f205d0e53c85"
down_revision: Union[str, None] = "92795f17c2a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "cat_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "product", type_="foreignkey")
    op.create_foreign_key(None, "product", "category", ["cat_id"], ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="foreignkey")
    op.create_foreign_key(None, "product", "category", ["cat_id"], ["id"])
    op.alter_column(
        "product",
        "cat_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
